module.exports = {
  MSG_SUCCESS : "200", //called with Helper::MSG_SUCCESS
  MSG_CREATED : "201",
  MSG_ERROR : "204", //called with Helper::MSG_ERROR
  MSG_REGISTER_CONFLICT : "209",
  MSG_TWILLO : "400",
  MSG_UNAUTHORIZED : "401",
  MSG_FORBIDDEN : "403",
  NOT_FOUND : "404",
  HTTP_METHOD_NOT_ALLOWED : "405",
  MSG_CONFLICT : "409", //called with Helper::MSG_CONFLICT
  MSG_GONE : "410",
  EXPECTATION_FAILED : "417",
  UNPROCESSABLE_ENTITY : "422",
  INTERNAL_SERVER_ERROR : "500"
};
